version: '3'
services:
  prometheus:
    command:
      - --config.file=/etc/prometheus/prometheus.development.yml
    volumes:
      - ./services/prometheus:/etc/prometheus
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=bechdel_lists_development
    ports:
      - "${POSTGRES_LOCAL_PORT:-5432}:5432"
  api:
    image: 'bechdel-lists-api'
    volumes:
      - ./services/api:/app
    environment:
      - RAILS_ENV=development
      - SEED_USER_NAME
      - SEED_USER_EMAIL
    ports:
      - "5000:5000"
    depends_on:
      - postgres
  client:
    image: 'bechdel-lists-client'
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./services/client:/app
    depends_on:
      - api
      - nginx
      - postgres
  nginx:
    image: 'bechdel-lists-nginx'
    build:
      args:
        listen_env: development
    ports:
      - "${NGINX_LOCAL_PORT:-3001}:80"
    volumes:
      - ./services/nginx:/etc/nginx/certs # hack to prevent missing path errors in lieu of a production compose file.
  ping:
    image: 'bechdel-lists-ping'
    environment:
      - HOST=host.docker.internal:${NGINX_LOCAL_PORT:-3001}
