version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=bechdel_demo
  nginx:
    image: 'jbrunton/bechdel-lists-nginx:latest'
    restart: always
    build:
      context: ./nginx
    ports:
      - 3001:80
  api:
    image: 'jbrunton/bechdel-lists-api:latest'
    build:
      context: ./api
    ports:
      - 9229:9229
    environment:
      - POSTGRES_HOST=postgres
      - SERVER_PORT=5000
      - GOOGLE_CLIENT_ID=729453438306-js80sgkqlrnot0elppoe7fblb51lkjv5.apps.googleusercontent.com
  client:
    image: 'jbrunton/bechdel-lists-client:latest'
    build:
      context: ./client
    environment:
      - VUE_APP_GOOGLE_CLIENT_ID=729453438306-js80sgkqlrnot0elppoe7fblb51lkjv5.apps.googleusercontent.com
