version: "3.8"

services:

  traefik:
    # The official v2 Traefik docker image
    image: traefik:v2.2
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-public
    labels:
      - traefik.http.routers.traefik-public-https.service=api@internal
      - traefik.http.routers.traefik-public-http.rule=Host(`traefik.localhost`)
      - traefik.http.services.traefik-public.loadbalancer.server.port=8080

networks:
  traefik-public:
    external: true
      