version: '3.8'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=bechdel_lists_development
    ports:
      - "${POSTGRES_LOCAL_PORT:-5432}:5432"
  api:
    image: 'bechdel-lists-api'
    volumes:
      - ./services/api:/app
    environment:
      - RAILS_ENV=development
      - SEED_USER_NAME
      - SEED_USER_EMAIL
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.bechdel-lists-api.rule=Host(`localhost`) && PathPrefix(`/api`)
      - traefik.http.routers.bechdel-lists-api.middlewares=api-stripprefix
      - traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api

  client:
    image: 'bechdel-lists-client'
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./services/client:/app
    ports:
      - "5001:5001"
    depends_on:
      - api
      - postgres
    labels:
      - "traefik.http.routers.bechdel-lists-client.rule=Host(`localhost`)"
      # - traefik.enable=true
      # - traefik.docker.network=traefik-public
      # - traefik.http.routers.bechdel-lists-client.rule=Host(`client.localhost`)
  
  # nginx:
  #   image: 'bechdel-lists-nginx'
  #   build:
  #     args:
  #       listen_env: development
  #   ports:
  #     - "${NGINX_LOCAL_PORT:-3001}:80"
  #   volumes:
  #     - ./services/nginx:/etc/nginx/certs # hack to prevent missing path errors in lieu of a production compose file.

networks:
  traefik-public:
    external: true
