version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.18.1
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.$PROMETHEUS_ENVIRONMENT.yml
    volumes:
      - $PROMETHEUS_DIR:/etc/prometheus
  grafana:
    image: grafana/grafana:7.0.0
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    volumes:
      - $GRAFANA_DIR/provisioning/:/etc/grafana/provisioning/
