version: '3'
services:
  nginx:
    image: "jbrunton/bechdel-lists-nginx:${TAG?}"
    restart: always
    build:
      context: ./services/nginx
    ports:
      - 80:80
      - 443:443
    volumns:
      - /home/deployer/certs:/etc/nginx/certs
  api:
    image: "jbrunton/bechdel-lists-api:${TAG?}"
    build:
      context: ./services/api
    ports:
      - 9229:9229
    environment:
      - NODE_ENV=production
      - SERVER_PORT=5000
      - GOOGLE_CLIENT_ID=729453438306-js80sgkqlrnot0elppoe7fblb51lkjv5.apps.googleusercontent.com
      - POSTGRES_CONNECTION
  client:
    image: "jbrunton/bechdel-lists-client:${TAG?}"
    build:
      context: ./services/client
    environment:
      - VUE_APP_GOOGLE_CLIENT_ID=729453438306-js80sgkqlrnot0elppoe7fblb51lkjv5.apps.googleusercontent.com
