version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=bechdel_demo
    ports:
      - 5432:5432
  api:
    image: 'bechdel-lists-api'
    volumes:
      - /app/node_modules
      - ./api:/app
    command: npm run debug
    environment:
      - NODE_ENV=development
  client:
    image: 'bechdel-lists-client'
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
  nginx:
    image: 'bechdel-lists-nginx'
