version: '3'
services:
  nginx:
    image: "jbrunton/bechdel-lists-nginx:${TAG?}"
    restart: always
    build:
      context: ./services/nginx
      args:
        listen_env: ${NGINX_LISTEN_ENV:-production}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${NGINX_CERTS_DIR:-/home/deployer/certs}:/etc/nginx/certs
  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:0.7.0
    ports:
      - 9113:9113
    environment:
      - SCRAPE_URI=http://nginx/stub_status
    depends_on:
      - nginx
  api:
    image: "jbrunton/bechdel-lists-api:${TAG?}"
    build:
      context: ./services/api
    ports:
      - 9229:9229
    environment:
      - RAILS_ENV=production
      - PORT=5000
      - GOOGLE_CLIENT_ID=729453438306-js80sgkqlrnot0elppoe7fblb51lkjv5.apps.googleusercontent.com
      - POSTGRES_CONNECTION
      - POSTGRES_DISABLE_SSL
      - RAILS_MASTER_KEY
      - RAILS_LOG_TO_STDOUT=1
  client:
    image: "jbrunton/bechdel-lists-client:${TAG?}"
    build:
      context: ./services/client
      args:
        build_version: $BUILD_VERSION
        google_client_id: 729453438306-js80sgkqlrnot0elppoe7fblb51lkjv5.apps.googleusercontent.com
