version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=bechdel_demo
    ports:
      - 5432:5432
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - 3000:80
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    ports:
      - 9229:9229
    environment:
      - POSTGRES_HOST=postgres
      - SERVER_PORT=5000
      - GOOGLE_CLIENT_ID=952635847674-ocr6762iqhjkvtb988fclnfs4trr6qqr.apps.googleusercontent.com
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - VUE_APP_GOOGLE_CLIENT_ID=952635847674-ocr6762iqhjkvtb988fclnfs4trr6qqr.apps.googleusercontent.com
