version: '3'
services:
  nginx:
    image: 'jbrunton/bechdel-lists-nginx:latest'
    restart: always
    build:
      context: ./nginx
    ports:
      - 3001:80
  api:
    image: 'jbrunton/bechdel-lists-api:latest'
    build:
      context: ./api
    ports:
      - 9229:9229
    environment:
      - NODE_ENV=production
      - SERVER_PORT=5000
      - GOOGLE_CLIENT_ID=729453438306-js80sgkqlrnot0elppoe7fblb51lkjv5.apps.googleusercontent.com
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
  client:
    image: 'jbrunton/bechdel-lists-client:latest'
    build:
      context: ./client
    environment:
      - VUE_APP_GOOGLE_CLIENT_ID=729453438306-js80sgkqlrnot0elppoe7fblb51lkjv5.apps.googleusercontent.com
