version: '3'
services:
  cadvisor:
    image: gcr.io/google-containers/cadvisor:v0.36.0
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - nginx
      - api
      - client
  nginx:
    image: "jbrunton/bechdel-lists-nginx:${TAG?}"
    restart: always
    build:
      context: ./services/nginx
      args:
        listen_env: ${NGINX_LISTEN_ENV:-production}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${NGINX_CERTS_DIR:-/home/deployer/certs}:/etc/nginx/certs
  api:
    image: "jbrunton/bechdel-lists-api:${TAG?}"
    build:
      context: ./services/api
    ports:
      - 9229:9229
    environment:
      - RAILS_ENV=production
      - PORT=5000
      - GOOGLE_CLIENT_ID=729453438306-js80sgkqlrnot0elppoe7fblb51lkjv5.apps.googleusercontent.com
      - POSTGRES_CONNECTION
      - POSTGRES_DISABLE_SSL
      - RAILS_MASTER_KEY
      - RAILS_LOG_TO_STDOUT=1
  client:
    image: "jbrunton/bechdel-lists-client:${TAG?}"
    build:
      context: ./services/client
      args:
        build_version: $BUILD_VERSION
        google_client_id: 729453438306-js80sgkqlrnot0elppoe7fblb51lkjv5.apps.googleusercontent.com
  ping:
    image: "jbrunton/bechdel-lists-ping:${TAG}"
    build:
      context: ./services/ping
    environment:
      - PING_TARGET_HOST
    depends_on:
      - api
