scrape_configs:
  - job_name: cadvisor
    scrape_interval: 15s
    static_configs:
    - targets:
      - cadvisor:8080
  - job_name: api
    scrape_interval: 15s
    static_configs:
    - targets:
      - api:5000
