scrape_configs:
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets:
      - cadvisor:8080
  - job_name: api
    scrape_interval: 5s
    static_configs:
    - targets:
      - api:5000
  - job_name: node
    scrape_interval: 5s
    static_configs:
    - targets:
      - bechdel-lists.jbrunton.com:9100
rule_files:
  - /etc/prometheus/rules.yml
  - /etc/prometheus/alerts.yml
