---
apiVersion: v1
kind: Service
metadata:
  name: api-cluster-ip-service
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    component: api
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
  ports:
  - port: 5001
    targetPort: 5001
  selector:
    component: client
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kbld.k14s.io/images: |
      - Metas:
        - Tag: 0.2.20-ddee6fc1-4220-49ef-a9ba-6c3b30678e1f
          Type: resolved
          URL: jbrunton/bechdel-lists-api:0.2.20-ddee6fc1-4220-49ef-a9ba-6c3b30678e1f
        URL: index.docker.io/jbrunton/bechdel-lists-api@sha256:056a2274268b7af4f544b28f2f1818e1f014f96bd853668e1efe667cf07c91fc
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
      - env:
        - name: PORT
          value: "5000"
        - name: GOOGLE_CLIENT_ID
          value: 729453438306-js80sgkqlrnot0elppoe7fblb51lkjv5.apps.googleusercontent.com
        - name: POSTGRES_CONNECTION
          valueFrom:
            secretKeyRef:
              key: postgres-connection
              name: postgres-connection
        image: index.docker.io/jbrunton/bechdel-lists-api@sha256:056a2274268b7af4f544b28f2f1818e1f014f96bd853668e1efe667cf07c91fc
        name: api
        ports:
        - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kbld.k14s.io/images: |
      - Metas:
        - Tag: 0.2.20-ddee6fc1-4220-49ef-a9ba-6c3b30678e1f
          Type: resolved
          URL: jbrunton/bechdel-lists-client:0.2.20-ddee6fc1-4220-49ef-a9ba-6c3b30678e1f
        URL: index.docker.io/jbrunton/bechdel-lists-client@sha256:f4a782dd2bbf9c700ea5e326b9b14f8a826cab2daf84fd1776fd49ea248d408b
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: client
  template:
    metadata:
      labels:
        component: client
    spec:
      containers:
      - env:
        - name: VUE_APP_GOOGLE_CLIENT_ID
          value: 729453438306-js80sgkqlrnot0elppoe7fblb51lkjv5.apps.googleusercontent.com
        image: index.docker.io/jbrunton/bechdel-lists-client@sha256:f4a782dd2bbf9c700ea5e326b9b14f8a826cab2daf84fd1776fd49ea248d408b
        name: client
        ports:
        - containerPort: 5001
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-connection
  namespace: default
spec:
  encryptedData:
    postgres-connection: AgCNzHYm/Y3oRY7lyOPrt/013gsBqAQd4yjhwW8cUhQl72xxsaNbUyypJmLN2dP8HJOQD0UNd1LiKw4Y/Z4PiJiGrQROCzlp36OeIAsIg4VqvYB/f0GA8YRvspvbIeHsVF7ay4o4ZTnVfC5akxgvjuSdgfUH1zHv/FiuKt5XLtVwafkinC2Wh/MHeElM6fHVUMzErOz509dK4O4WCdU0SzzBgyiMyKL05dYd6JYGDaDHf26Wi8dCq6gwQyhNfm+PubPP9kYu9PqvqvoUkZNJICZaV+3RysgY1gwiCZgKI51INtVooG+ANICh62yUqDJzYfbZ5wh+GxmunKpMTz+B9CnvuSHfUnhixL2oe6DJIgTpUvrk6QyeAx8mEzoVEvMNLnAfS5CtyetjHcGMkBlij4DR99wZNwOEuBWbM10ybX1Fba3nkdbpyvrL6kJYyFt4SJ1Dnszb0ncEAQ/C95JvrhNpnRRFHRvzRyRmZ2iEp2fqSfMQtS96+dEk/1GXOfCNvUlkBxdu2wNtDdExjqbzv/HlhDJhFmjKT7DlIwHqe6mcpE+gfP7y8iEx+000hSYfQkc5po3YhHwAaLnnLWD747la/fMf24Tx7//bLpmSmb20VXCTkrvG/726O4tZi/dFnrnFH5kb/ciqpCVRBKRllwkvvDZFEDJzRGUtHV/2W6T+OfhHu/Jb4CN0Zf/KUrL80k8CWCQ5WXgRPmzsqtIc82/7vIAV1A/i+XCxGDS5JnLSJBVHTKHqOHiKloAMjiMzQf0xU6kkLTGirU2cOi1OjdOg9DhOv0SO2883McjfPBHCkc3W3YJgd2VVznyIWStvYi/P9zGn0ClLRlFHnYlP9ZD0+NFN+FyCh4Y2mOV99UOhln2edro0yvWOWq1Mlhts
  template:
    metadata:
      creationTimestamp: null
      name: postgres-connection
      namespace: default
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: staging-bechdel-lists-jbrunton-com-tls
spec:
  commonName: staging.bechdel-lists.jbrunton.com
  dnsNames:
  - staging.bechdel-lists.jbrunton.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  secretName: staging-bechdel-lists-jbrunton-com-cert
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: john_brunton@live.co.uk
    privateKeySecretRef:
      name: letsencrypt-staging
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: ingress-service
spec:
  rules:
  - host: staging.bechdel-lists.jbrunton.com
    http:
      paths:
      - backend:
          serviceName: client-cluster-ip-service
          servicePort: 5001
        path: /?(.*)
      - backend:
          serviceName: api-cluster-ip-service
          servicePort: 5000
        path: /api/?(.*)
  tls:
  - hosts:
    - staging.bechdel-lists.jbrunton.com
    secretName: staging-bechdel-lists-jbrunton-com-cert
