metadata:
  annotations:
    kbld.k14s.io/images: |
      - Metas:
        - Tag: v0.36.0
          Type: resolved
          URL: gcr.io/google-containers/cadvisor:v0.36.0
        URL: gcr.io/google-containers/cadvisor@sha256:16bc6858dc5b7063c7d89153ad6544370eb79cb27a1b8d571f31b98673f7a324
      - Metas:
        - Tag: 0.2.19-18531929-f506-488e-acde-71813fb2fd00
          Type: resolved
          URL: jbrunton/bechdel-lists-api:0.2.19-18531929-f506-488e-acde-71813fb2fd00
        URL: index.docker.io/jbrunton/bechdel-lists-api@sha256:b40ec78362ac69b4cb74f37f19d5c992a072a173f6dac36d4cac62ea6fb03a5f
      - Metas:
        - Tag: 0.2.19-18531929-f506-488e-acde-71813fb2fd00
          Type: resolved
          URL: jbrunton/bechdel-lists-client:0.2.19-18531929-f506-488e-acde-71813fb2fd00
        URL: index.docker.io/jbrunton/bechdel-lists-client@sha256:54182f7f2a6a9481cbf065655b4bab97a40ed584412be7b14afd80b2f9eaf035
      - Metas:
        - Tag: 0.2.19-18531929-f506-488e-acde-71813fb2fd00
          Type: resolved
          URL: jbrunton/bechdel-lists-nginx:0.2.19-18531929-f506-488e-acde-71813fb2fd00
        URL: index.docker.io/jbrunton/bechdel-lists-nginx@sha256:1ae0ba67d084704fef02c5c64918b9d95ce43a26c8f874363b5c30ad10aeebab
      - Metas:
        - Tag: 0.7.0
          Type: resolved
          URL: nginx/nginx-prometheus-exporter:0.7.0
        URL: index.docker.io/nginx/nginx-prometheus-exporter@sha256:4058e755536f642a33780c83c00647e9363a21527c7cfcebbf4b373e027119c4
services:
  api:
    environment:
      GOOGLE_CLIENT_ID: 729453438306-js80sgkqlrnot0elppoe7fblb51lkjv5.apps.googleusercontent.com
      PORT: '5000'
      POSTGRES_CONNECTION: null
      POSTGRES_DISABLE_SSL: null
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: '1'
      RAILS_MASTER_KEY: null
    image: >-
      index.docker.io/jbrunton/bechdel-lists-api@sha256:b40ec78362ac69b4cb74f37f19d5c992a072a173f6dac36d4cac62ea6fb03a5f
    ports:
      - '9229:9229/tcp'
  cadvisor:
    container_name: cadvisor
    depends_on:
      - api
      - client
      - nginx
    image: >-
      gcr.io/google-containers/cadvisor@sha256:16bc6858dc5b7063c7d89153ad6544370eb79cb27a1b8d571f31b98673f7a324
    ports:
      - '8080:8080/tcp'
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker:/var/lib/docker:ro'
  client:
    image: >-
      index.docker.io/jbrunton/bechdel-lists-client@sha256:54182f7f2a6a9481cbf065655b4bab97a40ed584412be7b14afd80b2f9eaf035
  nginx:
    image: >-
      index.docker.io/jbrunton/bechdel-lists-nginx@sha256:1ae0ba67d084704fef02c5c64918b9d95ce43a26c8f874363b5c30ad10aeebab
    ports:
      - '80:80/tcp'
      - '443:443/tcp'
    restart: always
    volumes:
      - '/home/deployer/certs:/etc/nginx/certs:rw'
  nginx_exporter:
    depends_on:
      - nginx
    environment:
      SCRAPE_URI: 'http://nginx/stub_status'
    image: >-
      index.docker.io/nginx/nginx-prometheus-exporter@sha256:4058e755536f642a33780c83c00647e9363a21527c7cfcebbf4b373e027119c4
    ports:
      - '9113:9113/tcp'
version: '3.0'

