networks:
  traefik-public:
    external: true
    name: traefik-public
services:
  api:
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - >-
          traefik.http.routers.bechdel-lists-api.rule=Host(`$HOST`) &&
          PathPrefix(`/api`)
        - >-
          traefik.http.routers.bechdel-lists-api.middlewares=api-stripprefix,https-redirect
        - traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api
        - traefik.http.routers.bechdel-lists-api.entrypoints=https
        - traefik.http.routers.bechdel-lists-api.tls=true
        - traefik.http.routers.bechdel-lists-api.tls.certresolver=le
        - traefik.http.services.bechdel-lists-api.loadbalancer.server.port=5000
      mode: replicated
      replicas: 1
    environment:
      GOOGLE_CLIENT_ID: 729453438306-js80sgkqlrnot0elppoe7fblb51lkjv5.apps.googleusercontent.com
      HOST: $HOST
      PORT: '5000'
      POSTGRES_CONNECTION: null
      POSTGRES_DISABLE_SSL: null
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: '1'
      RAILS_MASTER_KEY: null
    image: >-
      jbrunton/bechdel-lists-api@sha256:f46db641ed09dffb176a671ffba661da430f1589510d9b1bedd145c4cc1eb5a5
    networks:
      default: null
      traefik-public: null
    ports:
      - published: 9229
        target: 9229
  client:
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.bechdel-lists-client.rule=Host(`$HOST`)
        - traefik.http.routers.bechdel-lists-client.entrypoints=https
        - traefik.http.routers.bechdel-lists-client.tls=true
        - traefik.http.routers.bechdel-lists-client.tls.certresolver=le
        - >-
          traefik.http.services.bechdel-lists-client.loadbalancer.server.port=5001
      mode: replicated
      replicas: 1
    image: >-
      jbrunton/bechdel-lists-client@sha256:f64c288040e134468e0c36df0b816aa6327668bb78f680fca58bebdc9be96975
    networks:
      traefik-public: null
version: '3.8'

