services:
  api:
    environment:
      GOOGLE_CLIENT_ID: 729453438306-js80sgkqlrnot0elppoe7fblb51lkjv5.apps.googleusercontent.com
      NODE_ENV: production
      POSTGRES_CONNECTION: null
      SERVER_PORT: '5000'
    image: >-
      jbrunton/bechdel-lists-api@sha256:04fb79916761df68b92c149a284c4677e4866085a91e5797dc9e3d0026dec39e
    ports:
      - '9229:9229/tcp'
  client:
    environment:
      VUE_APP_GOOGLE_CLIENT_ID: 729453438306-js80sgkqlrnot0elppoe7fblb51lkjv5.apps.googleusercontent.com
    image: >-
      jbrunton/bechdel-lists-client@sha256:257a4c56df6333084060573f386719f6cbe649e03e825e8188fd161b66b3b480
  nginx:
    image: >-
      jbrunton/bechdel-lists-nginx@sha256:f6f56ad3b5ba2a39b1c94a6668ee5f9d340a6d86f02c7b58e432736bfec91d2c
    ports:
      - '80:80/tcp'
    restart: always
version: '3.0'

