services:
  api:
    environment:
      GOOGLE_CLIENT_ID: 729453438306-js80sgkqlrnot0elppoe7fblb51lkjv5.apps.googleusercontent.com
      PORT: '5000'
      POSTGRES_CONNECTION: null
      POSTGRES_DISABLE_SSL: null
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: '1'
      RAILS_MASTER_KEY: null
    image: >-
      jbrunton/bechdel-lists-api@sha256:73a994b06b6cb29328507cf4cbf6916f8d93f8df48284dc06d9b5071054ba114
    ports:
      - '9229:9229/tcp'
  cadvisor:
    container_name: cadvisor
    depends_on:
      - api
      - client
      - nginx
    image: >-
      gcr.io/google-containers/cadvisor@sha256:16bc6858dc5b7063c7d89153ad6544370eb79cb27a1b8d571f31b98673f7a324
    ports:
      - '8080:8080/tcp'
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker:/var/lib/docker:ro'
  client:
    image: >-
      jbrunton/bechdel-lists-client@sha256:1fa24a629690af026d5a3a2de16ddf982b3b005a1455368897a316ad032dfab9
  nginx:
    image: >-
      jbrunton/bechdel-lists-nginx@sha256:440541d590414c83c35cb21c2564d3e5f03eaa53fd602638206d70ef8f3b8cc6
    ports:
      - '80:80/tcp'
      - '443:443/tcp'
    restart: always
    volumes:
      - '/home/deployer/certs:/etc/nginx/certs:rw'
  nginx_exporter:
    depends_on:
      - nginx
    environment:
      SCRAPE_URI: 'http://nginx/stub_status'
    image: >-
      nginx/nginx-prometheus-exporter@sha256:4058e755536f642a33780c83c00647e9363a21527c7cfcebbf4b373e027119c4
    ports:
      - '9113:9113/tcp'
version: '3.0'

