services:
  api:
    environment:
      GOOGLE_CLIENT_ID: 729453438306-js80sgkqlrnot0elppoe7fblb51lkjv5.apps.googleusercontent.com
      NODE_ENV: production
      POSTGRES_CONNECTION: null
      SERVER_PORT: '5000'
    image: >-
      jbrunton/bechdel-lists-api@sha256:a40996d4ce6faf654aff1f9b968905314efba6921c0b87dc8b6857ad63c7f806
    ports:
      - '9229:9229/tcp'
  client:
    environment:
      VUE_APP_GOOGLE_CLIENT_ID: 729453438306-js80sgkqlrnot0elppoe7fblb51lkjv5.apps.googleusercontent.com
    image: >-
      jbrunton/bechdel-lists-client@sha256:c8f2ddf5f44dcf22a6b3c42c8a17efcce20c87618598322b57eb9c26dfd3bfe1
  nginx:
    image: >-
      jbrunton/bechdel-lists-nginx@sha256:4c5ae91092d1f36e341a5c4cb0f8648103b5c2e5d4cb47729cca26ce47cbfb23
    ports:
      - '80:80/tcp'
    restart: always
version: '3.0'

