networks:
  traefik-public:
    external: true
    name: traefik-public
services:
  api:
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - >-
          traefik.http.routers.bechdel-lists-api.rule=Host(`dummy`) &&
          PathPrefix(`/api`)
        - >-
          traefik.http.routers.bechdel-lists-api.middlewares=api-stripprefix,https-redirect
        - traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api
        - traefik.http.routers.bechdel-lists-api.entrypoints=https
        - traefik.http.routers.bechdel-lists-api.tls=true
        - traefik.http.routers.bechdel-lists-api.tls.certresolver=le
        - traefik.http.services.bechdel-lists-api.loadbalancer.server.port=5000
      mode: replicated
      replicas: 1
    environment:
      GOOGLE_CLIENT_ID: 729453438306-js80sgkqlrnot0elppoe7fblb51lkjv5.apps.googleusercontent.com
      HOST: dummy
      PORT: '5000'
      POSTGRES_CONNECTION: null
      POSTGRES_DISABLE_SSL: null
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: '1'
      RAILS_MASTER_KEY: null
    image: >-
      jbrunton/bechdel-lists-api@sha256:ef0c965e5660811d7ec4c67a7f30a27372706d77649bcf6ce24d2b3b840b6f02
    networks:
      default: null
      traefik-public: null
    ports:
      - published: 9229
        target: 9229
  client:
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.bechdel-lists-client.rule=Host(`dummy`)
        - traefik.http.routers.bechdel-lists-client.entrypoints=https
        - traefik.http.routers.bechdel-lists-client.tls=true
        - traefik.http.routers.bechdel-lists-client.tls.certresolver=le
        - >-
          traefik.http.services.bechdel-lists-client.loadbalancer.server.port=5001
      mode: replicated
      replicas: 1
    image: >-
      jbrunton/bechdel-lists-client@sha256:8d43630df58c5621fd3995102d5bc015c5e9b6e14dacd138891a53edd2faddc7
    networks:
      traefik-public: null
version: '3.8'

