services:
  api:
    environment:
      GOOGLE_CLIENT_ID: 729453438306-js80sgkqlrnot0elppoe7fblb51lkjv5.apps.googleusercontent.com
      PORT: '5000'
      POSTGRES_CONNECTION: null
      POSTGRES_DISABLE_SSL: null
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: '1'
      RAILS_MASTER_KEY: null
    image: >-
      jbrunton/bechdel-lists-api@sha256:52d6ff159fc4de7953c8b9e9512668eb1222554df173eb63695c4a7b02596018
    ports:
      - '9229:9229/tcp'
  client:
    image: >-
      jbrunton/bechdel-lists-client@sha256:5954bce89744d7d87f87301905375e91b7cde61672c5fa634cc3a7452dbf379e
  nginx:
    depends_on:
      - api
      - client
    image: >-
      jbrunton/bechdel-lists-nginx@sha256:ae80d73cad4696cd2ff207e8d1c75c79b604164ff37b00b74e10fad7aa25c95f
    ports:
      - '80:80/tcp'
      - '443:443/tcp'
    restart: always
    volumes:
      - '/home/deployer/certs:/etc/nginx/certs:rw'
version: '3.0'

