apiVersion: v1
kind: Service
metadata:
  name: api-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: api
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: api
          image: jbrunton/bechdel-lists-api:0.2.16-41c0ed0a-c2ae-4720-92f5-6041605363c5
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: '5000'
            - name: POSTGRES_HOST
              value: postgres-cluster-ip-service
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_DB
              value: bechdel_lists_development
            - name: POSTGRES_CONNECTION
              value: postgres://postgres_user:postgres_password@postgres-cluster-ip-service:5432/bechdel_lists_development
            - name: GOOGLE_CLIENT_ID
              value: 729453438306-js80sgkqlrnot0elppoe7fblb51lkjv5.apps.googleusercontent.com
