apiVersion: v1
kind: Service
metadata:
  name: postgres-node-port
spec:
  type: NodePort
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      nodePort: 32000
  selector:
    component: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: api-node-port
spec:
  type: NodePort
  ports:
    - name: api
      port: 3000
      targetPort: 3000
      nodePort: 32010
  selector:
    component: api
