name: ci-build

on:
  push:
    branches:
      - master

env:
  DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
  DOCKER_USERNAME: jbrunton
  FORCE_COLOR: 1
        
jobs:

  build_check:
    runs-on: ubuntu-latest
    outputs:
      buildRequired: ${{ steps.check.outputs.buildRequired }}
      
    steps:
      - uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: check manifest
        id: check
        run: |
          npm run ci:build:check -- --output-file check.env

          source check.env
          echo "::set-output name=buildRequired::$BUILD_REQUIRED"

  build:
    runs-on: ubuntu-latest
    if: ${{ needs.build_check.outputs.buildRequired == true }}    
    needs: build_check

    steps:
      - uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: docker login
        run: echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: build
        run: npm run ci:build

      - name: commit
        run: |
          git config --global user.email "jbrunton-ci-minion@outlook.com"
          git config --global user.name "jbrunton-ci-minion"
          
          npm run ci:build:commit
          
          git push origin HEAD:master
