name: ci-deploy

on:
  deployment

env:
  CI: 1
  DEPLOYMENT: ${{ toJson(github.event.deployment) }}
  
jobs:

  configure:
    runs-on: ubuntu-latest

    steps:
      - name: 'Deployment pending'
        uses: 'deliverybot/status@master'
        with:
          state: 'pending'
          token: '${{ secrets.GITHUB_TOKEN }}'

  build:
    if: ${{ github.event.deployment.task == 'build' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'build'
        run: echo "Running build for ${GITHUB_REF}, ${DEPLOYMENT}"

  deploy:
    if: ${{ github.event.deployment.task == 'deploy' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'deploy'
        run: echo "Running deployment for ${GITHUB_REF}, ${DEPLOYMENT}"

  update_status:
    needs: [ build, deploy ]
    runs-on: ubuntu-latest

    steps:
      - name: 'notify success'
        if: success()
        uses: 'deliverybot/status@master'
        with:
          state: 'success'
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: 'notify failure'
        if: failure()
        uses: 'deliverybot/status@master'
        with:
          state: 'failure'
          token: '${{ secrets.GITHUB_TOKEN }}'