name: ci-deploy

on:
  deployment

env:
  DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
  DOCKER_USERNAME: jbrunton

  CI: 1
  FORCE_COLOR: 1

  TARGET_BRANCH: list-204

jobs:

  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.deployment.task == 'deploy' }}

    env:
      ENVIRONMENT: ${{ github.event.deployment.environment }}

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_ADMIN_ACCESS_TOKEN }}

      - name: 'Deployment pending'
        uses: 'deliverybot/status@master'
        with:
          state: 'pending'
          token: '${{ secrets.GITHUB_TOKEN }}'
      
      - name: npm install
        run: npm install

      - name: deployment info
        id: deployment_info
        run: npx ci set-outputs deployment-info $ENVIRONMENT

      - name: copy files
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ steps.deployment_info.outputs.host }}
          USERNAME: deployer
          KEY: ${{ secrets.DEPLOYER_SSH_KEY }}
        with:
          source: "${{ steps.deployment_info.outputs.buildFile }},monitoring,docker-compose.monitoring.yml"
          overwrite: true
          target: .

      - name: deploy
        uses: appleboy/ssh-action@master
        env:
          HOST: ${{ steps.deployment_info.outputs.host }}
          USERNAME: deployer
          KEY: ${{ secrets.DEPLOYER_SSH_KEY }}
          RAILS_MASTER_KEY: ${{ secrets.RAILS_PRODUCTION_MASTER_KEY }}
          POSTGRES_CONNECTION: ${{ secrets.POSTGRES_PRODUCTION_CONNECTION }}
          BUILD_FILE: ${{ steps.deployment_info.outputs.buildFile }}
          BUILD_VERSION: ${{ steps.deployment_info.outputs.buildVersion }}
        with:
          script: |
            ln -sf $BUILD_FILE docker-compose.yml
            export BUILD_VERSION
            export POSTGRES_CONNECTION
            export RAILS_MASTER_KEY
            docker stack deploy bechdel-lists -c docker-compose.yml
          envs: POSTGRES_CONNECTION,RAILS_MASTER_KEY,BUILD_FILE,BUILD_VERSION

      - name: 'commit'
        run: |
          git config --global user.email "jbrunton-ci-minion@outlook.com"
          git config --global user.name "jbrunton-ci-minion"
          
          npx ci commit deployment $ENVIRONMENT
          
          git push origin HEAD:$TARGET_BRANCH
  
      - name: 'notify success'
        if: success()
        uses: 'deliverybot/status@master'
        with:
          state: 'success'
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: 'notify failure'
        if: failure()
        uses: 'deliverybot/status@master'
        with:
          state: 'failure'
          token: '${{ secrets.GITHUB_TOKEN }}'

  update_manifest:
    runs-on: ubuntu-latest
    if: ${{ github.event.deployment.task == 'update_manifest' }}

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_ADMIN_ACCESS_TOKEN }}

      - name: npm install
        run: npm install

      - name: Update manifest
        env:
          ENVIRONMENT: ${{ github.event.deployment.payload.environment }}
          VERSION: ${{ github.event.deployment.payload.version }}    
        run: |
          git config --global user.email "jbrunton-ci-minion@outlook.com"
          git config --global user.name "jbrunton-ci-minion"
          
          npx ci update-manifest $VERSION $ENVIRONMENT
          
          git push origin HEAD:$TARGET_BRANCH
