name: ci-manifest-check

on:
  push:
    branches:
      - demo-90

env:
  CI: 1

jobs:

  manifest_check:
    runs-on: ubuntu-latest
    outputs:
      deploymentMatrix: ${{ steps.check.outputs.deploymentMatrix }}
      
    steps:
      - uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: check manifest
        id: check
        run: npx ci check manifest
  
  start:
    needs: manifest_check
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.manifest_check.outputs.deploymentMatrix) }}

    steps:
      - uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: generate payload
        id: payload
        env:
          TASK: ${{ matrix.task }}
          ENVIRONMENT: ${{ matrix.environment }}
          BUILD_VERSION: ${{ matrix.version }}
        run: npx ci generate ${TASK}-payload $BUILD_VERSION $ENVIRONMENT

      - name: start deployment
        env:
          PAYLOAD: ${{ steps.payload.outputs.payload }}
          GITHUB_TOKEN: ${{ secrets.CI_MINION_ACCESS_TOKEN }}
        run: echo '${PAYLOAD}' | hub api "repos/jbrunton/bechdel-demo/deployments" --input -
