name: ci-manifest-check

on:
  push:
    branches:
      - demo-90

jobs:

  manifest_check:
    runs-on: ubuntu-latest
    outputs:
      jobsMatrix: ${{ steps.check.outputs.jobsMatrix }}
      
    steps:
      - uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: check manifest
        id: check
        run: echo "::set-output name=jobsMatrix::{\"include\":[{\"type\":\"build\",\"environment\":\"ci-build\"},{\"type\":\"deployment\",\"environment\":\"production\"}]}"

  start:
    needs: manifest_check
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.manifest_check.outputs.jobsMatrix) }}
    env:
      matrix: ${{ toJson(matrix) }}
    steps:
    - run: echo $MATRIX
