name: ci-run
on:
  deployment

jobs:
  ci-run:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v2

      - name: run command
        env:
          COMMAND: ${{ github.event.deployment.payload.command }}"
        run: |
          echo "Running npm run ${COMMAND}"
          echo "payload - ${{ toJson(github.event.deployment.payload) }}"
