name: ci-repo-dispatch

on:
  repository_dispatch:
    types: [tests-passed]

jobs:

  log_event:
    if: github.event.branch == 'master'
    runs-on: ubuntu-latest

    steps:
      - name: echo event
        env:
          EVENT: ${{ toJson(github.event) }}
        run: echo "$EVENT"
