name: ci-run
on:
  deployment

jobs:
  ci-run:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: run command
        env:
          TASK: ${{ github.event.deployment.task }}
          ENVIRONMENT: ${{ github.event.deployment.environment }}
          PAYLOAD: ${{ toJson(github.event.deployment.payload) }}
          ARGS: ${{ github.event.deployment.payload.args }}

        run: |
          git config --global user.email "jbrunton-ci-minion@outlook.com"
          git config --global user.name "jbrunton-ci-minion"

          echo "deployment - ${{ toJson(github.event.deployment) }}"

          export COMMAND="npm run ${TASK} -- --environment ${ENVIRONMENT} ${ARGS}"
          echo "Running npm run ${COMMAND}"
          ${COMMAND}

          git push origin HEAD:${GITHUB_REF}
