name: ci-run
on:
  deployment

jobs:
  ci-run:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v2

      - name: 'Deployment pending'
        uses: 'deliverybot/status@master'
        with:
          state: 'pending'
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: npm install
        run: npm install

      - name: run command
        env:
          TASK: ${{ github.event.deployment.task }}
          ENVIRONMENT: ${{ github.event.deployment.environment }}
          PAYLOAD: ${{ github.event.deployment.payload }}

        run: |
          git config --global user.email "jbrunton-ci-minion@outlook.com"
          git config --global user.name "jbrunton-ci-minion"

          echo "deployment - ${{ toJson(github.event.deployment) }}"

          export COMMAND="npm run ${TASK} -- --environment ${ENVIRONMENT} ${PAYLOAD}"
          echo "Running ${COMMAND}"
          ${COMMAND}

          git push origin HEAD:${GITHUB_REF}

        - name: 'notify success'
          if: success()
          uses: 'deliverybot/status@master'
          with:
            state: 'success'
            token: '${{ secrets.GITHUB_TOKEN }}'
    
        - name: 'notify failure'
          if: failure()
          uses: 'deliverybot/status@master'
          with:
            state: 'failure'
            token: '${{ secrets.GITHUB_TOKEN }}'
