name: ci-test

on: push

env:
  CI: 1
  FORCE_COLOR: 1
  WORKSPACE: ${{ github.workspace }}


jobs:

  unit_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: ['api', 'client']

    steps:
      - uses: actions/checkout@v2

      - name: run
        env:
          SERVICE: ${{ matrix.service }}
        run: |
          cd ${WORKSPACE}/services/${SERVICE}
          npm install
          npm run test:unit

  integration_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: ['api', 'client']

    steps:
      - uses: actions/checkout@v2

      - name: copy .env
        run: cp ci/ci.env .env

      - name: build
        run: docker-compose build

      - name: run
        run: |
          docker-compose up -d
          docker-compose run api npm run db:test:create
          ./ci/integration_tests/${SERVICE}.sh
