name: ci-test

on: push

env:
  CI: 1
  FORCE_COLOR: 1
  WORKSPACE: ${{ github.workspace }}


jobs:

  unit_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: ['api', 'client']

    steps:
      - uses: actions/checkout@v2

      - name: run
        env:
          SERVICE: ${{ matrix.service }}
        run: ./ci/unit_test.sh

  # integration_tests:
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       service: ['api', 'client']

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: copy .env
  #       run: cp ci/ci.env .env

  #     - name: build
  #       run: docker-compose build

  #     - name: run
  #       env:
  #         SERVICE: ${{ matrix.service }}
  #       run: |
  #         docker-compose up -d
  #         docker-compose run api npm run db:test:create

  #         if [ "$SERVICE" = 'client' ]
  #         then
  #           cd ./ser
  #         else
  #           echo "running $SERVICE"
  #         fi
