name: ci-builder

on: push

env:
  CI: 1
  FORCE_COLOR: 1

jobs:

  test:
    runs-on: ubuntu-latest

    env:
      WORKSPACE: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v2

      - name: npm install
        run: |
          cd ${WORKSPACE}/services/api
          npm install

      - name: unit tests
        run: |
          cd ${WORKSPACE}/services/api
          npm run test:unit
      
      - name: build
      run: docker-compose build
  
      - name: integration tests
      run: |
        docker-compose up -d
        docker-compose run npm run test:integration

