name: CI

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      DOCKER_USERNAME: jbrunton

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: ./ci/build.sh

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - uses: actions/checkout@v2
  
    - name: Deploy
      uses: appleboy/ssh-action@master
      env:
        DEPLOYMENT_SHA: ${{ github.sha }}
        COMPOSE_FILE: docker-compose.yml
        HOST: ${{ secrets.DEPLOY_HOST }}
        USERNAME: deployer
        KEY: ${{ secrets.DEPLOYER_SSH_KEY }}
        POSTGRES_USER: ${{ secrets.POSTGRES_PRODUCTION_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PRODUCTION_PASSWORD }}
        POSTGRES_HOST: ${{ secrets.POSTGRES_PRODUCTION_HOST }}
        POSTGRES_PORT: ${{ secrets.POSTGRES_PRODUCTION_PORT }}
      with:
        script: |
          cd bechdel-demo
          docker-compose -f docker-compose.yml down
          git fetch
          git checkout $DEPLOYMENT_SHA
          docker-compose -f docker-compose.yml pull
          export POSTGRES_USER=$POSTGRES_USER
          export POSTGRES_PASSWORD=$POSTGRES_PASSWORD
          export POSTGRES_HOST=$POSTGRES_HOST
          export POSTGRES_PORT=$POSTGRES_PORT
          docker-compose -f docker-compose.yml up -d
        envs: DEPLOYMENT_SHA,COMPOSE_FILE,POSTGRES_USER,POSTGRES_PASSWORD,POSTGRES_HOST,POSTGRES_PORT
