name: Deploy

on:
  push:
    tags:
      - v*
    branches:
      - demo-44

env:
  DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
  DOCKER_USERNAME: jbrunton
        
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Parse tag
      run: ./ci/parse_tag.sh

    - name: Build the Docker image
      run: ./ci/build.sh

  deploy:
    needs: build
    runs-on: ubuntu-latest

    env:
      GITHUB_REF: ${{ github.ref }}
      GITHUB_SHA: ${{ github.sha }}

    steps:
    - uses: actions/checkout@v2

    - name: Parse tag
      run: ./ci/parse_tag.sh

    - name: Generate Deployment
      run: ./ci/generate_deployment.sh
  
    - name: Deploy
      uses: appleboy/ssh-action@master
      env:
        HOST: ${{ secrets.DEPLOY_HOST }}
        USERNAME: deployer
        KEY: ${{ secrets.DEPLOYER_SSH_KEY }}
        POSTGRES_CONNECTION: ${{ secrets.POSTGRES_PRODUCTION_CONNECTION }}
      with:
        script: |
          cd bechdel-demo
          git fetch
          git checkout $DEPLOYMENT_SHA

          export POSTGRES_CONNECTION
          export DEPLOYMENT_FILE

          ./ci/deploy.sh
        envs: POSTGRES_CONNECTION,DEPLOYMENT_SHA,DEPLOYMENT_FILE
