name: Deploy

on:
  push:
    branches:
      - demo-59

env:
  DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
  DOCKER_USERNAME: jbrunton
        
jobs:

  check:
    runs-on: ubuntu-latest

    outputs:
      deploymentRequired: ${{ steps.check.outputs.deploymentRequired }}
      buildIds: ${{ steps.check.outputs.buildIds }}
      
    steps:
      - uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: Check manifest
        id: check
        run: ./ci/check_manifest.sh

      - name: Build
        if: ${{ steps.check.outputs.deploymentRequired == true }}
        env:
          DEPLOYMENT_REQUIRED: ${{ steps.check.outputs.deploymentRequired }}
        run: echo "Running build, DEPLOYMENT_REQUIRED=$DEPLOYMENT_REQUIRED"

      - name: No Build
        if: ${{ steps.check.outputs.deploymentRequired == false }}
        env:
          DEPLOYMENT_REQUIRED: ${{ steps.check.outputs.deploymentRequired }}
        run: echo "No build required, DEPLOYMENT_REQUIRED=$DEPLOYMENT_REQUIRED"

  build:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.deploymentRequired == true }}

    steps:
      - uses: actions/checkout@v2
 
      - name: Build
        if: ${{ needs.check.outputs.deploymentRequired == true }}
        env:
          DEPLOYMENT_REQUIRED: ${{ needs.check.outputs.deploymentRequired }}
        run: echo "Running build, DEPLOYMENT_REQUIRED=$DEPLOYMENT_REQUIRED"

      - name: No Build
        if: ${{ needs.check.outputs.deploymentRequired == false }}
        env:
          DEPLOYMENT_REQUIRED: ${{ needs.check.outputs.deploymentRequired }}
        run: echo "No build required, DEPLOYMENT_REQUIRED=$DEPLOYMENT_REQUIRED"


  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Parse tag
  #     run: ./ci/parse_tag.sh

  #   - name: Build the Docker image
  #     run: ./ci/build.sh

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   env:
  #     GITHUB_REF: ${{ github.ref }}
  #     GITHUB_SHA: ${{ github.sha }}

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Parse tag
  #     run: ./ci/parse_tag.sh

  #   - name: Generate Deployment
  #     run: ./ci/generate_deployment.sh
  
  #   - name: Deploy
  #     uses: appleboy/ssh-action@master
  #     env:
  #       HOST: ${{ secrets.DEPLOY_HOST }}
  #       USERNAME: deployer
  #       KEY: ${{ secrets.DEPLOYER_SSH_KEY }}
  #       POSTGRES_CONNECTION: ${{ secrets.POSTGRES_PRODUCTION_CONNECTION }}
  #     with:
  #       script: |
  #         cd bechdel-demo
  #         git fetch
  #         git checkout $DEPLOYMENT_SHA

  #         export POSTGRES_CONNECTION
  #         export DEPLOYMENT_FILE

  #         ./ci/deploy.sh
  #       envs: POSTGRES_CONNECTION,DEPLOYMENT_SHA,DEPLOYMENT_FILE
