name: CI

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      DOCKER_USERNAME: jbrunton

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: ./ci/build.sh

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - uses: actions/checkout@v2
  
    - name: Deploy
      uses: appleboy/ssh-action@master
      env:
        DEPLOYMENT_SHA: ${{ github.sha }}
        HOST: ${{ secrets.DEPLOY_HOST }}
        USERNAME: deployer
        KEY: ${{ secrets.DEPLOYER_SSH_KEY }}
        POSTGRES_CONNECTION: ${{ secrets.POSTGRES_PRODUCTION_CONNECTION }}
      with:
        script: |
          export COMPOSE_FILE=docker-compose.yml
          cd bechdel-demo
          docker-compose down
          git fetch
          git checkout $DEPLOYMENT_SHA
          docker-compose pull
          export POSTGRES_CONNECTION=$POSTGRES_CONNECTION
          docker-compose up -d --no-build
        envs: POSTGRES_CONNECTION
