name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      DOCKER_USERNAME: jbrunton

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: echo "skipping build" # ./ci/build.sh

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - uses: actions/checkout@v2

    - name: Generate deployment file
      run: |
        export DEPLOYMENT_NAME="release_$(date '+%Y-%m-%d_%H%M%S')"
        export DOCKER_COMPOSE_FILE="docker-compose-$DEPLOYMENT_NAME.yml"
        echo "::set-env name=DEPLOYMENT_NAME::$DEPLOYMENT_NAME"
        echo "::set-env name=DOCKER_COMPOSE_FILE::$DOCKER_COMPOSE_FILE"
        cp docker-compose.yml $DOCKER_COMPOSE_FILE
        echo "Created $DOCKER_COMPOSE_FILE"

    - name: Copy deployment file
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.DEPLOY_HOST }}
        USERNAME: deployer
        KEY: ${{ secrets.DEPLOYER_SSH_KEY }}
      with:
        source: $DOCKER_COMPOSE_FILE
        target: "/home/deployer"
  
    - name: Restart services
      uses: appleboy/ssh-action@master
      env:
        HOST: ${{ secrets.DEPLOY_HOST }}
        USERNAME: deployer
        KEY: ${{ secrets.DEPLOYER_SSH_KEY }}
      with:
        script: |
          docker-compose -f $DOCKER_COMPOSE_FILE down
          docker-compose pull
          docker-compose up -d
        envs: DOCKER_COMPOSE_FILE
