name: Deploy

on:
  push:
    tags:
      - v*
    branches:
      - demo-44

env:
  DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
  DOCKER_USERNAME: jbrunton
        
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Parse tag
      run: ./ci/parse_tag.sh

    - name: Build the Docker image
      run: echo "Running for TAG=${TAG}. Skipping build." # ./ci/build.sh

  deploy:
    needs: build
    runs-on: ubuntu-latest

    env:
      GITHUB_REF: ${{ github.ref }}
      GITHUB_SHA: ${{ github.sha }}

    steps:
    - uses: actions/checkout@v2

    - name: Parse tag
      run: ./ci/parse_tag.sh

    - name: Generate Deployment
      run: ./ci/generate_deployment.sh
  
    - name: Deploy
      uses: appleboy/ssh-action@master
      env:
        HOST: ${{ secrets.DEPLOY_HOST }}
        USERNAME: deployer
        KEY: ${{ secrets.DEPLOYER_SSH_KEY }}
        POSTGRES_CONNECTION: ${{ secrets.POSTGRES_PRODUCTION_CONNECTION }}
      with:
        script: |
          echo "DEPLOYMENT_FILE: $DEPLOYMENT_FILE"
          export COMPOSE_FILE=$DEPLOYMENT_FILE
          
          cd bechdel-demo
          git fetch
          git checkout origin/master
          
          export POSTGRES_CONNECTION
          docker-compose up --project-directory=. --detach --no-build --remove-orphans
        envs: POSTGRES_CONNECTION,DEPLOYMENT_SHA,DEPLOYMENT_FILE
