name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      SHA: $(git rev-parse HEAD)

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: echo "Running build for SHA $SHA" # docker build . --file Dockerfile --tag my-image-name:$(SHA)
      
