name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      DOCKER_USERNAME: jbrunton

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: echo "skipping build" # ./ci/build.sh

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - uses: actions/checkout@v2
  
    - name: Deploy
      uses: appleboy/ssh-action@master
      env:
        DEPLOYMENT_SHA: ${{ github.sha }}
        COMPOSE_FILE: docker-compose.yml
        HOST: ${{ secrets.DEPLOY_HOST }}
        USERNAME: deployer
        KEY: ${{ secrets.DEPLOYER_SSH_KEY }}
      with:
        script: |
          cd bechdel-demo
          docker-compose down
          git checkout $DEPLOYMENT_SHA
          docker-compose pull
          docker-compose up -d
        envs: DEPLOYMENT_SHA,COMPOSE_FILE
